#!/usr/bin/env bash

# rm -f ./plots/data/perf_data.csv
# rm -f plot_previous.pdf
# mv plot.pdf plot_previous.pdf
# rm -f plot.pdf

# sizes6208=(16 17 32 34 64 68 128 136 272 544)

# for h in ${sizes6208[@]}; do
#     for w in ${sizes6208[@]}; do
#         for nbThread in $(seq 8 16); do 
#             OMP_NUM_THREADS=$nbThread ./run -k life -v tiled_omp -tw $w -th $h -s 2176 -a otca_off -n -i 20;
#         done
#     done
# done

# ./plots/easyplot.py


####
# Script to compare each frame of two different variant of the same kernel
####

i=5000

rm traces/data/*.png
rm traces/data/old/*.png
./run -k life -v seq -ts 8 -s 256 -n -i $i --thumbnails
mv traces/data/*.png traces/data/old/
./run -k life -v tiled_omp_lazy -ts 8 -s 256 -n -i $i --thumbnails

cd traces/data

for filename in $(ls *.png); do
    echo $filename;
    diff $filename old/$filename
done
