#!/usr/bin/env bash

# rm -f ./plots/data/perf_data.csv
# rm -f plot_previous.pdf
# mv plot.pdf plot_previous.pdf
# rm -f plot.pdf

# sizes6208=(16 17 32 34 64 68 128 136 272 544)

# for h in ${sizes6208[@]}; do
#     for w in ${sizes6208[@]}; do
#         for nbThread in $(seq 8 16); do 
#             OMP_NUM_THREADS=$nbThread ./run -k life -v tiled_omp -tw $w -th $h -s 2176 -a otca_off -n -i 20;
#         done
#     done
# done

# ./plots/easyplot.py


###
# Script to compare each frame of two different variant of the same kernel
###

i=1000
s=1024
lazy=tiled_omp_lazy
omp=tiled_omp
tiled=tiled

using=$lazy

try=100

make

for t in $(seq 0 $try); do
    rm dump-life-seq-dim-*-iter-*.png;
    rm dump-life-$using-dim-*-iter-*.png;

    ./run -k life -v seq -a random -s $s -n -i $i --dump 2> /dev/null;
    OMP_PLACES=cores OMP_SCHEDULE="dynamic" OMP_NUM_THREADS=16 ./run -k life -a random -v $using -ts 16 -s $s -n -i $i --dump 2> /dev/null;

    res=$(diff -s dump-life-seq-dim-$s-iter-$i.png dump-life-$using-dim-$s-iter-$i.png | cut -d " " -f 6);
    echo $res
    if [ "$res" = "differ" ]; then
        break;
    fi
done

echo "done"

######################

# i=2000

# rm traces/data/*.png
# rm traces/data/old/*.png
# ./run -k life -v seq -s 256 -n -i $i --thumbnails --trace
# mv traces/data/*.png traces/data/old/
# ./run -k life -v tiled_omp_lazy -ts 16 -s 256 -n -i $i --thumbnails --trace

# cd traces/data

# for filename in $(ls *.png); do
#     diff -s $filename old/$filename
# done