#!/usr/bin/env bash

make -j 12

variants=(
  seq
  vec_seq
  vec_tiled
  vec_omp_tiled_lazy
)

iter=100
threads=$(seq 1 48)

rm -f plots/data/perf_data.csv

for t in ${threads[*]}; do
  for v in ${variants[*]}; do
    OMP_PLACES=cores OMP_NUM_THREADS=$t OMP_SCHEDULE=static ./run -k life_vec -v $v -tw 388 -th 388 -s 6208 -n -i $iter -a meta3x3;
  done
done

for t in ${threads[*]}; do
  OMP_NUM_THREADS=$t ./run -k life_ocl -o -tw 388 -th 388 -s 6208 -n -i $iter -a meta3x3;q
done

plots/easyplot.py
mv plot.pdf speedup.pdf
